from fpdf import FPDF
import os
from datetime import datetime

class PDF(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42)
        self.rect(0, 0, 210, 30, 'F')
        self.set_y(10)
        self.set_font('Arial', 'B', 20)
        self.set_text_color(0, 255, 204)
        self.cell(0, 10, 'QNOSE MULTIPLEX DIAGNOSTIC', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, 'Comprehensive Quantum-Classical Pathological Analysis', 0, 1, 'C')
        self.ln(15)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by QNose System', 0, 0, 'C')

def main():
    print("--- Generating Full Analysis Report ---")
    pdf = PDF()
    
    # Page 1: Title Page
    pdf.add_page()
    pdf.set_font('Arial', 'B', 24)
    pdf.cell(0, 50, '', 0, 1)
    pdf.cell(0, 20, 'QNose Results & Analytics', 0, 1, 'C')
    pdf.set_font('Arial', '', 14)
    pdf.cell(0, 10, 'Multi-Disease Diagnostics using Quantum Machine Learning', 0, 1, 'C')
    pdf.cell(0, 10, f'Report Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'C')
    
    # Page 2: Accuracy Table 
    pdf.add_page()
    pdf.set_font('Arial', 'B', 18)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, ' 1. Model Architectures & Benchmarks', 0, 1, 'L', fill=True)
    pdf.ln(5)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 8, "The QNose system assesses VOC profiles via a suite of parallel AI agents. The current 27-disease model trains over simulated quantum Hilbert spaces in order to benchmark true quantum-advantage.")
    
    # Page 3: Confusion Matrices
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'Confusion Matrices (Classical vs Quantum)', 0, 1)
    if os.path.exists('confusion_matrices.png'):
        pdf.image('confusion_matrices.png', x=10, w=190)
        
    # Page 4: Quantum Circuit diagram
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'Quantum Circuit Architecture', 0, 1)
    if os.path.exists('quantum_circuit.png'):
        pdf.image('quantum_circuit.png', x=10, w=190)
        
    # Page 5: SHAP Explanation
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'SHAP Explainability (Why was it flagged?)', 0, 1)
    if os.path.exists('shap_explanation.png'):
        pdf.image('shap_explanation.png', x=15, w=170)
        
    # Page 6: Conclusion
    pdf.add_page()
    pdf.set_font('Arial', 'B', 18)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, ' 4. Conclusion & Quantum Advantage', 0, 1, 'L', fill=True)
    pdf.ln(5)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 10, "Quantum Machine Learning (QML) models like QNose leverage complex, high-dimensional Hilbert spaces. While Classical SVMs perform well, the hardware-efficient Entangling Quantum Kernel estimates similarities between samples by evolving them via quantum entanglement and interference. This foundational shift unearths non-linear correlations in complex biomarkers, offering a promising avenue for early and non-invasive detection across 27 distinct disease topologies.")
    
    pdf.output('QNose_Results.pdf')
    print("Generated QNose_Results.pdf")

if __name__ == '__main__':
    main()